### ISSUE TITLE
output to console when exit status 1

### ISSUE THREAD

**Issue by simonhjoerg** [codeskyblue/go-sh#10]
Im encountering a issue where a exit status 1 command gives output to the console.

This is a issue for me as i need a specific text to appear in the console rather than the command output (the reason for this is, its used for a monitoring check and expects a certain syntax).

The pseudo example code is:
`
package := "randompackage"

output, err := sh.Command("dpkg-query", "--showformat='${Version}'", "--show", package).Output()
fmt.Println(err)
`

This will result in the following output in the console
 dpkg-query: no packages found matching randompackage <------------- This being the commands failing output
exit status 1 <------------- This being the fmt.println

Let me know if you want any other info

Is there anyway to mute the output ?

**Comment by codeskyblue** [comment]
If you use the standard lib `os/exec`, will it be ok?

**Comment by simonhjoerg** [comment]
Sorry for the delay in getting back to you.

When using the standard lib os/exec i don't see this behavior.

Here is some sample code:
`package main

import (
        "fmt"
	"os/exec"
	"os"
)

func main(){
	out, err := exec.Command("/usr/bin/dpkg-query", "--show", "sdf").Output()
	fmt.Println(out)
	fmt.Println(err)
}
`

Notice how the package here is "sdf" 
It doesn't exist on my system so the output of this is:
```
[]
exit status 1
```

If i change that to "zip" which exists on my system, i get the desired output:
```
[122 105 112 9 51 46 48 45 56 10]
<nil>
```

So when the package doesn't exist, i don't get the forced output to the console
(like: dpkg-query: no packages found matching sdf)
printed to the console.
Which is the behavior i was hoping to see with go-sh

**Comment by codeskyblue** [comment]
Well, the default behavior is send the stderr to the console. Because this is also normal shell script does.

If you want to mute the stderr, Need to set Stderr to nil, for example:

```
package main

import (
    "log"

    "github.com/codeskyblue/go-sh"
)

func main() {
    sess := sh.NewSession()
    sess.Stderr = nil 
    _, err := sess.Command("python", "-V").Output()
    log.Println("Err:", err)
}
```

**Comment by codeskyblue** [comment]
Maybe I should closed it.
