### ISSUE TITLE
Writing a bash like shell

### ISSUE THREAD

**Issue by faeronsayn** [codeskyblue/go-sh#13]
Can we do something like this with the following with this plugin
```
$ > myshell
myshell > mycommand1 
myshell > mycommand2 some_sub_command --a some_args
myshell > exit
$ > 
```

Essentially have a shell that has it's own commands?

**Comment by codeskyblue** [comment]
What you said is a shell, I remember that someone has implemented a shell using golang.

**Comment by faeronsayn** [comment]
For anyone wondering i've found this: https://github.com/abiosoft/ishell
