### ISSUE TITLE
Possible  goroutine  leak?

### ISSUE THREAD

**Issue by jiabiaoreal** [codeskyblue/go-sh#26]
//  the following  code is from  pipe.go
func (s *Session) WaitTimeout(timeout time.Duration) (err error) {
	select {
	case <-time.After(timeout):
		s.Kill(syscall.SIGKILL)
		return ErrExecTimeout
	case err = <-Go(s.Wait):
		return err
	}
}

func Go(f func() error) chan error {
	ch := make(chan error)
	go func() {
		ch <- f()
	}()
	return ch
}

if timeout happends,  go func() {ch <- f() }(), will never return, since 
[A receive from an unbuffered channel happens before the send on that channel completes. ](https://tip.golang.org/ref/mem#tmp_7)

**Comment by codeskyblue** [comment]
That sounds reasonable
