### ISSUE TITLE
 mutil command is hangling and no return

### ISSUE THREAD

**Issue by huangjiasingle** [codeskyblue/go-sh#28]
sh.Command("sh", "-c", fmt.Sprintf("oc delete all -n %v %v", namespace, labels)).
Command("sh", "-c", fmt.Sprintf("oc delete service -n %v %v", namespace, labels)).
Command("sh", "-c", fmt.Sprintf("oc delete configmap -n %v %v", namespace, labels)).
Command("sh", "-c", fmt.Sprintf("oc delete secret -n %v %v", namespace, labels)).
Output()

not return

**Comment by codeskyblue** [comment]
this is pipeline, not multi command

**Comment by huangjiasingle** [comment]
@codeskyblue  yeal , l got it. thanks
