### ISSUE TITLE
Is it possible to work with interactive shell (like mongo)?

### ISSUE THREAD

**Issue by sqshq** [codeskyblue/go-sh#30]
I'm trying to figure out, is it possible to work with interactive shell commands? 

e.g. as a first step, connect to mongodb:
`mongo --quiet --host=localhost blog`

then perform arbitrary number of commands, like
`db.getCollection('posts').find({status:'INACTIVE'})`

and then
`exit`

**Comment by BadgerBadgerBadgerBadger** [comment]
Hi @sqshq . Could you share how you did this?

**Comment by codeskyblue** [comment]
Looks like missing such api
